const x = 20;

try {
    x = 10;
} catch (error) {
    console.log(`Erro aqui:${error}`);
}